# Generated by Django 4.1.1 on 2022-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirtelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_head', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=22)),
                ('data_with_rollover', models.CharField(max_length=50)),
                ('sms_per_day', models.CharField(max_length=22)),
                ('local_std_and_roaming_calls', models.CharField(max_length=20)),
                ('amazon_prime', models.CharField(max_length=20)),
            ],
        ),
    ]
